### ISSUE TITLE
Add more items to event

### ISSUE THREAD

**Issue by hulkoba** [GoodNightCouchSide/gncs-api#20]
## Das Event braucht mehr Felder:

- [ ] headliner: String -  required
- [ ] support: array; 
- [ ] datetime : date (einlasszeit) iso
- [ ] links -> eventLinks umbenennen
- [ ] type : enum ['concert', festival', 'party']

```
datetime im controller: 
"start": {
  "time":"20:00:00",
  "date":"2012-04-18",
  "datetime":"2012-04-18T20:00:00-0800"
},
```

**Comment by tkdamian** [comment]
Wir könnten überlegen ob wir eine neue Tabelle mit artist erstellen, aber für den Anfang würde ich sagen reicht ein string.

Können gerne datum und zeit trennen.

Die Einlass-zeit wollten wir required machen, und die Startzeit des act wussten wir nicht so recht. Die frage wäre dann was die startzeit ist: Anfang vom headliner, Anfang vom ersten supporter etc.
