### ISSUE TITLE
Add Venues

### ISSUE THREAD

**Issue by hulkoba** [GoodNightCouchSide/gncs-api#21]
### We need
- [x] Routen `/venues`
- [x] Controller (CRUD)
- [x] Validator
- [x] Model (update)
- [x] documentation (mit Referenzen)
- [x] Tests

### Fields
- name | string | required
- description | string | required
- street | string | required
- streetnumber | string| required
- postcode | string | required
- city | string | required

### Additional fields (Vorschlag)
- url zur webseite
- ?

**Comment by tkdamian** [comment]
vielleicht noch links (facebook, bandcamp, etc)

ansonsten fällt mir nicht ein. Der Gedanke war da, dass wir später ein Wiki haben

**Comment by hulkoba** [comment]
Ein Venue hat auch ne bandcamp seite?
